### ISSUE TITLE
how to zoom in video by percentage

### ISSUE THREAD

**Issue by work3t** [pili-engineering/PLDroidPlayer#852]
I want to enlarge the video by a percentage, how to do this?

**Comment by work3t** [comment]
Hello, is dynamically changing the layout params by overriding OnLayout a bug? or its some other setting? Looking forward to your comments.

**Comment by zshbleaker** [comment]
We're looking into this issue. It's a bit strange as we found it in development and we thought it has been fixed.  Have you tried `invalidate()` and `requestLayout()` after updating layout params?

**Comment by work3t** [comment]
Yes I did try using invalidate() and requestLayout() but it did not fix it.

Further more, its when the app goes into background by clicking the menu button and resumes from the 'select app to resume' screen, issue occurs. 

![screen shot 2018-02-27 at 9 52 37 am](https://user-images.githubusercontent.com/35325736/36706246-fd60abac-1ba3-11e8-83fe-d0b988194c29.png)

When the app is resumed from clicking on the app icon, the screen becomes normal again.

**Comment by zshbleaker** [comment]
@work3t Could please upload your demo to cloud storage like DropBox or Droplr? Baidu Cloud is limited in my office network.

**Comment by work3t** [comment]
Here it is:
https://www.dropbox.com/s/w3g36x3vgj3yuxk/PLDroidPlayerDemo.zip?dl=0

**Comment by work3t** [comment]
@zshbleaker Where you able to get the files from dropbox?

**Comment by work3t** [comment]
Will there be an update for this one? I'm still hoping to do an upgrade once this is resolved.
